### PR TITLE
Docs/setup swagger

### LINKED ISSUE #9: [FEAT] - Swagger Docs
### What feature would you like to see?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Vyvy-vi**
# resolves #9
## Description
This PR adds support for `/api/docs` route, which automatically fetches content from Jsdoc annotated comments inside the code, along with documentation for some of the routes.

## Packages Added
- `swagger-jsdoc`
- `swagger-ui-express`

## How to add more documentation?
ref:
- `swagger-jsdoc` docs - https://github.com/Surnet/swagger-jsdoc/tree/v7/docs
- Swagger Editor - https://editor.swagger.io/

### CODE REVIEW

**Comment by j-dogcoder** [comment]
This looks super good @Vyvy-vi! Let me know when you are ready for it to be reviewed.

**Comment by j-dogcoder** [comment]
Hey @Vyvy-vi, any update?

**Comment by Vyvy-vi** [comment]
wupps, sorry for disappearing 😓

**Comment by j-dogcoder** [comment]
All good @Vyvy-vi! Is this ready for review yet?

**Comment by Vyvy-vi** [comment]
This PR is good to go.
Please merge this one in before making any changes to the API...

**Comment by j-dogcoder** [comment]
Sounds good @Vyvy-vi! I will review this now!

**Comment by j-dogcoder** [comment]
Failed to open page Safari ILZQklg5
 
Am I doing something wrong @Vyvy-vi?

**Comment by j-dogcoder** [comment]
OH!

**Comment by j-dogcoder** [comment]
We use app.ts not app.js

**Comment by j-dogcoder** [comment]
I will switch that over.

**Comment by j-dogcoder** [comment]
Huh. Just noticed it in app.ts as well.

**Comment by j-dogcoder** [comment]
@Vyvy-vi I am just getting a blank white window now.

**Comment by j-dogcoder** [comment]
Postman Postman W0B9IwHT
 Postman shows stuff, but I don't get anything in a browser window.

**Comment by Vyvy-vi** [comment]
> Failed to open page Safari ILZQklg5
> 
> Am I doing something wrong @Vyvy-vi?

Can you go to `http://127.0.0.1:8080/api/docs` ?

**Comment by Vyvy-vi** [comment]
Screenshot 2022-05-02 at 8 20 15 AM
It should look like this...

**Comment by Vyvy-vi** [comment]
Did you run `npm install` to update your packages?

**Comment by j-dogcoder** [comment]
Weird. It works fine on Google Chrome, but it's still not working on safari.

**Comment by j-dogcoder** [comment]
Any advice @Vyvy-vi?

**Comment by Vyvy-vi** [comment]
did going to `http://127.0.0.1:8000/api/docs` work in safari?

**Comment by Vyvy-vi** [comment]
Safari can't go to localhost sometimes, if the localhost isn't defined in your devices /etc/hosts

**Comment by j-dogcoder** [comment]
That seems to work!

**Review by j-dogcoder — APPROVED** [review]
🎉 LGTM 🎉

**Comment by j-dogcoder** [comment]
### Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labeled `help wanted` for additional opportunities to contribute.

**Discord Server:**
_We would love it if you joined our community discord server! Your contribution to the project make you eligible for special roles & perks._

**Pull request merged**
